sudo: required
dist: trusty

language: python
python:
  - "3.5"

before_install:
  - sudo apt-get install liblas-c3

install:
  - pip install -e .
  - pip install pytest
  - pip install pytest-benchmark

script:
  - pytest
  - py3dtiles info tests/pointCloudRGB.pnts

addons:
  apt:
    update: true

